# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustommodel',
            name='name1',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
